env: "local"

db_host: "postgres"
db_port: 5432
db_user: "postgres"
db_password: "example"
db_name: "l0"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

kafka:
  brokers:
    - "kafka:9092"
  topic: "orders"
  group_id: "l0_group"
